name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        workspace: ['workspace_dev', 'workspace_prod']
    steps:
    - name: Terraform Init
      run: echo "terraform init"

    - name: Terraform Format
      run: echo "terraform fmt -check"

    - name: Terraform Plan
      run: echo "terraform apply -out=.terraform-plan-${{ matrix.workspace }}" > .terraform-plan-${{ matrix.workspace }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: terraform-plan-${{ matrix.workspace }}
        path: .terraform-plan-${{ matrix.workspace }}


  terraform-apply-dev:
    needs: terraform-plan
    name: 'Terraform Apply Dev'
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan-workspace_dev
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: cat .terraform-plan-workspace_dev

  terraform-apply-prod:
    needs: terraform-plan
    name: 'Terraform Apply Prod'
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan-workspace_prod
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: cat .terraform-plan-workspace_prod
