name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        workspace: ['workspace_dev', 'workspace_prod']
    steps:
    - name: Terraform Init
      run: echo "terraform init"

    - name: Terraform Format
      run: echo "terraform fmt -check"

    - name: Terraform Plan
      run: echo "terraform plan -out=.terraform-plan-${{ matrix.workspace }}"


  # terraform-apply:
  #   name: 'Terraform Apply'
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #   - name: Terraform Apply
  #     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #     run: echo "terraform apply -auto-approve -out=.terraform-plan-$(WORKSPACE)
